(*Tests from testcases folder. 3 SAT (7,8,9) and 1 IMPL (11) fail to run 
because Coq runs out of memory*)
Add LoadPath "..".
Require Import msl.msl_standard.
Require Import share_dec_base.
Require Import share_equation_system.
Require Import share_simplifier.
Require Import share_solver.
Require Import fbool_solver.
Require Import share_solver_with_partition.

Module Tester.

 Module es := Equation_system sv_nat Share_Domain.
 Module esf := System_Features sv_nat es.
 Module bf := Bool_formula sv_nat.
 Module bsf := BF_solver sv_nat bf.
 Import es.
 Module solver := Solver_with_partition sv_nat es bf bsf.
 Import solver.

 Definition a1 : var := 0.
 Definition a2 : var := 1.
 Definition a3 : var := 2.
 Definition a4 : var := 3.
 Definition a5 : var := 4.
 Definition a6 : var := 5.
 Definition a7 : var := 6.
 Definition a8 : var := 7.
 Definition a9 : var := 8.
 Definition a10 : var := 9.
 Definition a11 : var := 10.
 Definition a12 : var := 11.
 Definition a13 : var := 12.
 Definition a14 : var := 13.
 Definition a15 : var := 14.
 Definition a16 : var := 15.
 Definition a17 : var := 16.
 Definition a18 : var := 17.
 Definition a19 : var := 18.
 Definition a20 : var := 19.
 Definition a21 : var := 20.
 Definition a : var := 21.
 Definition b : var := 22.
 Definition c : var := 23.
 Definition d : var := 24.
 Definition ses1 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a2,Vobject a3,Vobject a4)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a4,Vobject a5,Vobject a6)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a6,Vobject a7,Vobject a8)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a8,Vobject a9,Vobject a10)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a10,Vobject a11,Vobject a12)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a12,Vobject a13,Vobject a14)::(Vobject a13,Vobject a14,Vobject a15)::(Vobject a14,Vobject a15,Vobject a16)::(Vobject a15,Vobject a16,Vobject a17)::(Vobject a16,Vobject a17,Vobject a18)::(Vobject a17,Vobject a18,Vobject a19)::(Vobject a18,Vobject a19,Vobject a20)::nil).
 Definition ses2 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a2,Vobject a3,Vobject a4)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a4,Vobject a5,Vobject a6)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a6,Vobject a7,Vobject a8)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a8,Vobject a9,Vobject a10)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a10,Vobject a11,Vobject a12)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a12,Vobject a13,Vobject a14)::(Vobject a13,Vobject a14,Vobject a15)::(Vobject a14,Vobject a15,Vobject a16)::(Vobject a15,Vobject a16,Vobject a17)::(Vobject a16,Vobject a17,Vobject a18)::(Vobject a17,Vobject a18,Vobject a19)::(Vobject a18,Vobject a19,Vobject a20)::(Vobject a19,Vobject a20,Cobject (Share.top))::nil).
 Definition ses3 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a2,Vobject a3,Vobject a4)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a4,Vobject a5,Vobject a6)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a6,Vobject a7,Vobject a8)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a8,Vobject a9,Vobject a10)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a10,Vobject a11,Vobject a12)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a12,Vobject a13,Vobject a14)::(Vobject a13,Vobject a14,Vobject a15)::(Vobject a14,Vobject a15,Vobject a16)::(Vobject a15,Vobject a16,Vobject a17)::(Vobject a16,Vobject a17,Vobject a18)::(Vobject a17,Vobject a18,Vobject a19)::(Vobject a18,Vobject a19,Vobject a20)::(Vobject a19,Vobject a20,Cobject (Share.recompose (Share.top,Share.bot)))::nil).
 Definition ses4 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a13,Vobject a14,Vobject a15)::(Vobject a15,Vobject a16,Vobject a17)::(Vobject a17,Vobject a18,Vobject a19)::(Vobject a19,Vobject a20,Vobject a21)::nil).
 Definition ses5 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a13,Vobject a14,Vobject a15)::(Vobject a15,Vobject a16,Vobject a17)::(Vobject a17,Vobject a18,Vobject a19)::(Vobject a19,Vobject a20,Cobject (Share.top))::nil).
 Definition ses6 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a13,Vobject a14,Vobject a15)::(Vobject a15,Vobject a16,Vobject a17)::(Vobject a17,Vobject a18,Vobject a19)::(Vobject a19,Vobject a20,Cobject (Share.recompose (Share.bot,Share.top)))::nil).
 (*
 Definition ses7 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))))))))))::nil).
 Definition ses8 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))))))))))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::nil).
 Definition ses9 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))))))))))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::(Vobject a1,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.bot,Share.top)),Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.top,Share.bot))),Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.top,Share.bot)),Share.recompose (Share.recompose (Share.bot,Share.top),Share.recompose (Share.bot,Share.top))))),Vobject a3)::nil).
 *)
 Definition ses10 :=Sat_equation_system (nil) ((Vobject a1,Vobject a4)::(Vobject a2,Vobject a5)::(Vobject a3,Vobject a6)::(Vobject a7,Cobject (Share.top))::(Vobject a8,Cobject (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot)))::(Vobject a9,Cobject (Share.recompose (Share.recompose (Share.bot,Share.top),Share.top)))::nil) ((Vobject a1,Vobject a2,Vobject a7)::(Vobject a2,Vobject a3,Vobject a8)::(Vobject a3,Vobject a1,Vobject a9)::(Vobject a4,Vobject a5,Cobject (Share.top))::(Cobject (Share.top),Vobject a3,Vobject a7)::(Cobject (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot)),Cobject (Share.recompose (Share.bot,Share.top)),Vobject a10)::(Vobject a11,Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.top))::(Cobject (Share.top),Vobject a12,Vobject a7)::(Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.top))::nil).
 Definition ses11 :=Sat_equation_system (nil) ((Vobject a1,Vobject a4)::(Vobject a2,Vobject a5)::(Vobject a3,Vobject a6)::(Vobject a7,Cobject (Share.top))::(Vobject a8,Cobject (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot)))::(Vobject a9,Cobject (Share.recompose (Share.recompose (Share.bot,Share.top),Share.top)))::nil) ((Vobject a1,Vobject a2,Vobject a7)::(Vobject a2,Vobject a3,Vobject a8)::(Vobject a3,Vobject a1,Vobject a9)::(Vobject a4,Vobject a5,Cobject (Share.top))::(Cobject (Share.top),Vobject a3,Vobject a7)::(Cobject (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot)),Cobject (Share.recompose (Share.bot,Share.top)),Vobject a10)::(Vobject a11,Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.top))::(Cobject (Share.top),Vobject a12,Vobject a7)::(Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.top))::(Vobject a5,Vobject a6,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::nil).
 Definition ses12 :=Sat_equation_system (nil) ((Vobject a1,Vobject a2)::(Vobject a2,Vobject a3)::(Vobject a3,Vobject a4)::(Vobject a4,Vobject a5)::(Vobject a5,Vobject a6)::(Vobject a6,Vobject a7)::(Vobject a7,Vobject a8)::(Vobject a8,Vobject a9)::(Vobject a9,Vobject a10)::(Vobject a10,Vobject a11)::(Vobject a11,Vobject a12)::(Vobject a12,Vobject a13)::(Vobject a13,Vobject a14)::(Vobject a14,Vobject a15)::(Vobject a15,Vobject a16)::(Vobject a16,Vobject a17)::(Vobject a17,Vobject a18)::(Vobject a18,Vobject a19)::(Vobject a19,Vobject a20)::nil) (nil).

 Definition ses13 :=Sat_equation_system (nil) ((Vobject a1,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.top,Share.bot)))))))))))::(Vobject a3,Cobject (Share.top))::(Vobject a6,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.top,Share.bot)),Share.recompose (Share.recompose (Share.bot,Share.top),Share.recompose (Share.bot,Share.top)))))::(Vobject a7,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a8,Cobject (Share.top))::(Vobject a9,Cobject (Share.top))::(Vobject a10,Cobject (Share.top))::(Vobject a11,Cobject (Share.top))::(Vobject a12,Cobject (Share.top))::(Vobject a13,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a14,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a15,Cobject (Share.top))::(Vobject a17,Cobject (Share.top))::(Vobject a18,Cobject (Share.top))::(Vobject a19,Cobject (Share.top))::(Vobject a20,Cobject (Share.top))::nil) (nil).
 Definition ses14 :=Sat_equation_system (nil) ((Vobject a4,Vobject a5)::(Vobject a8,Vobject a9)::(Vobject a10,Vobject a11)::(Vobject a11,Vobject a12)::(Vobject a13,Vobject a14)::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.top,Share.bot)))))))))))::(Vobject a3,Cobject (Share.top))::(Vobject a6,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.top,Share.bot)),Share.recompose (Share.recompose (Share.bot,Share.top),Share.recompose (Share.bot,Share.top)))))::(Vobject a7,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a8,Cobject (Share.top))::(Vobject a9,Cobject (Share.top))::(Vobject a10,Cobject (Share.top))::(Vobject a11,Cobject (Share.top))::(Vobject a12,Cobject (Share.top))::(Vobject a13,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a14,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a15,Cobject (Share.top))::(Vobject a17,Cobject (Share.top))::(Vobject a18,Cobject (Share.top))::(Vobject a19,Cobject (Share.top))::(Vobject a20,Cobject (Share.top))::nil) (nil).
 Definition ses15 :=Sat_equation_system (nil) ((Vobject a1,Vobject a2)::(Vobject a4,Vobject a5)::(Vobject a8,Vobject a9)::(Vobject a10,Vobject a11)::(Vobject a11,Vobject a12)::(Vobject a13,Vobject a14)::(Vobject a1,Vobject a20)::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.top,Share.bot)))))))))))::(Vobject a3,Cobject (Share.top))::(Vobject a6,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.top,Share.bot)),Share.recompose (Share.recompose (Share.bot,Share.top),Share.recompose (Share.bot,Share.top)))))::(Vobject a7,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a8,Cobject (Share.top))::(Vobject a9,Cobject (Share.top))::(Vobject a10,Cobject (Share.top))::(Vobject a11,Cobject (Share.top))::(Vobject a12,Cobject (Share.top))::(Vobject a13,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a14,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject a15,Cobject (Share.top))::(Vobject a17,Cobject (Share.top))::(Vobject a18,Cobject (Share.top))::(Vobject a19,Cobject (Share.top))::(Vobject a20,Cobject (Share.top))::nil) (nil).
 Definition ses16 :=Sat_equation_system (nil) ((Vobject a1,Cobject (Share.top))::(Vobject a2,Cobject (Share.top))::(Vobject a3,Cobject (Share.top))::(Vobject a4,Cobject (Share.top))::(Vobject a5,Cobject (Share.top))::(Vobject a6,Cobject (Share.top))::(Vobject a7,Cobject (Share.top))::(Vobject a8,Cobject (Share.top))::(Vobject a9,Cobject (Share.top))::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.top)))::nil) (nil).
 Definition ses17 :=Sat_equation_system (nil) (nil) (nil).
 Definition is1 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::nil)).
 Definition is2 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a2)::nil) ((Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (nil) (nil) (nil)).
 Definition is3 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a2)::nil) ((Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (nil) ((Vobject a3,Cobject (Share.top))::nil) (nil)).
 Definition is4 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a1,Vobject a3,Cobject (Share.recompose (Share.bot,Share.top)))::nil),Impl_equation_system (nil) (nil) ((Vobject a1,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a2,Cobject (Share.recompose (Share.top,Share.bot)))::nil) (nil)).
 Definition is5 :=(Impl_equation_system (nil) (nil) (nil) (nil),Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a1)::(Vobject a2,Vobject a2)::(Vobject a3,Vobject a3)::(Vobject a4,Vobject a4)::(Vobject a5,Vobject a5)::(Vobject a6,Vobject a6)::(Vobject a7,Vobject a7)::(Vobject a8,Vobject a8)::(Vobject a9,Vobject a9)::(Vobject a10,Vobject a10)::nil) ((Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.top))::nil)).
 Definition is6 :=(Impl_equation_system (nil) (nil) (nil) (nil),Impl_equation_system (a11::nil) (nil) ((Vobject a1,Vobject a1)::(Vobject a2,Vobject a2)::(Vobject a3,Vobject a3)::(Vobject a4,Vobject a4)::(Vobject a5,Vobject a5)::(Vobject a6,Vobject a6)::(Vobject a7,Vobject a7)::(Vobject a8,Vobject a8)::(Vobject a9,Vobject a9)::(Vobject a10,Vobject a10)::(Vobject a11,Cobject (Share.top))::nil) ((Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.top))::nil)).
 Definition is7 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::nil) ((Vobject a1,Vobject a3,Cobject (Share.top))::(Vobject a5,Vobject a6,Vobject a7)::nil),Impl_equation_system (nil) (nil) (nil) (nil)).
 Definition is8 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::nil) ((Vobject a1,Vobject a3,Cobject (Share.top))::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a1,Vobject a1,Vobject a2)::nil),Impl_equation_system (nil) (nil) (nil) ((Vobject a8,Vobject a9,Vobject a10)::nil)).
 Definition is9 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::nil) ((Vobject a1,Vobject a3,Cobject (Share.top))::(Vobject a5,Vobject a6,Vobject a7)::nil),Impl_equation_system (nil) (nil) ((Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::nil) ((Vobject a4,Vobject a5,Vobject a3)::nil)).
 Definition is10 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a1,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::nil) ((Vobject a1,Vobject a3,Cobject (Share.top))::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::nil),Impl_equation_system (nil) (nil) ((Vobject a10,Vobject a11)::(Vobject a8,Cobject (Share.recompose (Share.top,Share.bot)))::nil) ((Vobject a8,Vobject a9,Vobject a10)::nil)).
 (*
 Definition is11 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))))))))))::nil),Impl_equation_system (nil) (nil) ((Vobject a2,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top)))::nil) (nil)).
 *)
 Definition is12 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a3)::(Vobject a2,Vobject a3)::nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.bot,Share.top))))))))))))))))))::nil),Impl_equation_system (nil) (nil) ((Vobject a2,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top),Share.top)))::nil) (nil)).
 Definition is13 :=(Impl_equation_system (nil) (nil) ((Vobject a1,Vobject a3)::nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.bot,Share.top))))))))))))))))))::(Vobject a3,Vobject a3,Vobject a3)::nil),Impl_equation_system (nil) (nil) ((Vobject a2,Cobject (Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.top,Share.recompose (Share.bot,Share.top))))))))))))))))))::nil) (nil)).
 Definition is14 :=(Impl_equation_system (nil) (nil) (nil) (nil),Impl_equation_system (nil) (nil) (nil) (nil)).
 Definition ses18 :=Sat_equation_system (nil) (nil) ((Vobject a,Vobject b,Cobject (Share.top))::(Vobject c,Vobject b,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject c,Vobject a,Cobject (Share.top))::nil).
 Definition ses19 :=Sat_equation_system (a::nil) ((Vobject a,Vobject a)::(Vobject a,Cobject (Share.top))::nil) ((Vobject a,Vobject a,Vobject a)::nil).
 Definition ses20 :=Sat_equation_system (a::nil) ((Vobject a,Vobject a)::(Vobject a,Cobject (Share.bot))::nil) ((Vobject a,Vobject a,Vobject a)::nil).
 Definition ses21 :=Sat_equation_system (a ::nil) (nil) ((Vobject a,Vobject b,Cobject (Share.top))::nil).
 Definition ses22 :=Sat_equation_system (a ::nil) (nil) ((Vobject a,Vobject b,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::nil).
 Definition ses23 :=Sat_equation_system (a ::nil) (nil) ((Vobject a,Vobject b,Cobject (Share.top))::(Vobject a,Vobject c,Cobject (Share.top))::(Vobject b,Vobject c,Cobject (Share.top))::nil).
 Definition ses24 :=Sat_equation_system (a ::nil) (nil) ((Vobject a,Vobject b,Cobject (Share.top))::(Vobject a,Vobject c,Cobject (Share.top))::(Vobject b,Vobject c,Cobject (Share.top))::(Vobject a,Vobject a,Vobject a)::nil).
 Definition ses25 :=Sat_equation_system (a ::nil) (nil) ((Vobject a,Vobject b,Cobject (Share.top))::(Vobject a,Vobject c,Cobject (Share.top))::(Vobject b,Vobject c,Cobject (Share.top))::(Vobject a,Vobject b,Vobject c)::nil).
 Definition ses26 :=Sat_equation_system (a1 ::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a3,Vobject a4,Vobject a1)::(Vobject a5,Vobject a6,Vobject a3)::(Vobject a7,Vobject a8,Vobject a5)::(Vobject a9,Vobject a10,Vobject a7)::(Vobject a11,Vobject a12,Vobject a9)::(Vobject a13,Vobject a14,Vobject a11)::(Vobject a15,Vobject a16,Vobject a13)::nil).
 Definition ses27 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a16)::nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a3,Vobject a4,Vobject a1)::(Vobject a5,Vobject a6,Vobject a3)::(Vobject a7,Vobject a8,Vobject a5)::(Vobject a9,Vobject a10,Vobject a7)::(Vobject a11,Vobject a12,Vobject a9)::(Vobject a13,Vobject a14,Vobject a11)::(Vobject a15,Vobject a16,Vobject a13)::nil).
 Definition ses28 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a3)::(Vobject a2,Vobject a4)::(Vobject a5,Cobject (Share.top))::nil) ((Vobject a1,Vobject a4,Vobject a5)::(Vobject a2,Vobject a3,Vobject a6)::nil).
 Definition ses29 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a2)::(Vobject a3,Cobject (Share.bot))::(Vobject a4,Cobject (Share.top))::(Vobject a5,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::nil) ((Vobject a1,Vobject a5,Vobject a6)::(Vobject a2,Vobject a7,Vobject a3)::nil).
 Definition ses30 :=Sat_equation_system (a1::nil) ((Vobject a1,Vobject a2)::(Vobject a3,Cobject (Share.bot))::(Vobject a4,Cobject (Share.top))::(Vobject a5,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::nil) ((Vobject a1,Vobject a5,Vobject a6)::(Vobject a2,Vobject a7,Vobject a3)::nil).
 Definition ses31 :=Sat_equation_system (nil) ((Vobject a1,Vobject a2)::(Vobject a3,Cobject (Share.bot))::(Vobject a4,Cobject (Share.top))::(Vobject a5,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::nil) ((Vobject a1,Vobject a5,Vobject a6)::(Vobject a2,Vobject a7,Vobject a3)::nil).
 Definition ses32 :=Sat_equation_system (a1::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))::(Vobject a1,Vobject a3,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::nil).
 Definition ses33 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))::(Vobject a1,Vobject a3,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::nil).
 Definition ses34 :=Sat_equation_system (a1::nil) ((Vobject a1,Vobject a2)::(Vobject a2,Vobject a3)::(Vobject a3,Vobject a4)::(Vobject a4,Vobject a5)::(Vobject a5,Vobject a6)::(Vobject a6,Vobject a7)::(Vobject a7,Vobject a8)::nil) (nil).
 Definition ses35 :=Sat_equation_system (a1::nil) ((Vobject a1,Vobject a2)::(Vobject a2,Vobject a3)::(Vobject a3,Vobject a4)::(Vobject a4,Vobject a5)::(Vobject a5,Vobject a6)::(Vobject a6,Vobject a7)::(Vobject a7,Vobject a8)::nil) ((Vobject a1,Vobject a4,Vobject a8)::nil).
 Definition ses36 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::(Vobject a4,Vobject a5,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::(Vobject a5,Vobject a6,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::(Vobject a6,Vobject a7,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))::(Vobject a7,Vobject a8,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))::nil).
 Definition ses37 :=Sat_equation_system (a1 ::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::(Vobject a4,Vobject a5,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::(Vobject a5,Vobject a6,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::(Vobject a6,Vobject a7,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))::(Vobject a7,Vobject a8,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))::nil).
 Definition ses38 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a8)::nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.bot,Share.top)))::(Vobject a3,Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::(Vobject a4,Vobject a5,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::(Vobject a5,Vobject a6,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::(Vobject a6,Vobject a7,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))::(Vobject a7,Vobject a8,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))::nil).
 Definition ses39 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a3,Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::nil).
 Definition ses40 :=Sat_equation_system (a1 ::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a3,Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::nil).
 Definition ses41 :=Sat_equation_system (a1 ::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a2,Vobject a3,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject a3,Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::nil).
 Definition ses42 :=Sat_equation_system (nil) (nil) ((Vobject a1,Vobject a1,Vobject a1)::(Vobject a2,Vobject a2,Vobject a2)::(Vobject a1,Vobject a2,Vobject a3)::nil).
 Definition ses43 :=Sat_equation_system (a1 ::nil) (nil) ((Vobject a1,Vobject a1,Vobject a1)::(Vobject a2,Vobject a2,Vobject a2)::(Vobject a1,Vobject a2,Vobject a3)::nil).
 Definition ses44 :=Sat_equation_system (a ::nil) ((Vobject a,Vobject d)::(Vobject b,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::nil) ((Vobject b,Vobject d,Vobject c)::(Vobject a,Vobject b,Vobject c)::nil).
 Definition ses45 :=Sat_equation_system (a ::nil) ((Vobject a,Vobject d)::(Vobject b,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))::nil) ((Vobject b,Vobject d,Vobject c)::(Vobject a,Vobject b,Vobject c)::(Vobject a,Vobject c,Vobject b)::nil).
 Definition ses46 :=Sat_equation_system (nil) ((Vobject a,Vobject b)::(Vobject c,Vobject a)::(Vobject d,Vobject b)::(Vobject c,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::(Vobject d,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot)))::nil) ((Vobject a,Vobject a,Vobject b)::(Vobject c,Vobject d,Vobject a)::nil).
 Definition ses47 :=Sat_equation_system (a ::nil) ((Vobject a,Vobject b)::(Vobject c,Vobject a)::(Vobject d,Vobject b)::(Vobject c,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::(Vobject d,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot)))::nil) ((Vobject a,Vobject a,Vobject b)::(Vobject c,Vobject d,Vobject a)::nil).
 Definition ses48 :=Sat_equation_system (a ::nil) ((Vobject a,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))::(Vobject b,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::(Vobject c,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))::(Vobject d,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::nil) (nil).
 Definition ses49 :=Sat_equation_system (a ::nil) ((Vobject a,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))::(Vobject b,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::(Vobject c,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))::(Vobject d,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot),Share.bot)))::nil) ((Vobject a,Vobject b,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))))))))::(Vobject c,Vobject d,Cobject (Share.top))::nil).
 Definition ses50 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a7,Vobject a8)::nil) ((Vobject a1,Vobject a3,Vobject a5)::(Vobject a2,Vobject a4,Vobject a6)::nil).
 Definition ses51 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a7,Vobject a8)::nil) ((Vobject a1,Vobject a3,Vobject a5)::(Vobject a2,Vobject a4,Vobject a6)::(Vobject a7,Vobject a8,Vobject a1)::nil).
 Definition ses52 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a7,Vobject a8)::nil) ((Vobject a1,Vobject a3,Vobject a5)::(Vobject a2,Vobject a4,Vobject a6)::(Vobject a7,Vobject a8,Vobject a8)::nil).
 Definition ses53 :=Sat_equation_system (a1 ::nil) ((Vobject a1,Vobject a2)::(Vobject a3,Vobject a4)::(Vobject a5,Vobject a6)::(Vobject a7,Vobject a8)::nil) ((Vobject a1,Vobject a3,Vobject a5)::(Vobject a2,Vobject a4,Vobject a6)::(Vobject a7,Vobject a8,Vobject a8)::nil).
 Definition is15 :=(Impl_equation_system (nil) (a::nil) (nil) ((Vobject a,Vobject a,Vobject a)::nil),Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::nil)).
 Definition is16 :=(Impl_equation_system (nil) (a1 ::nil) ((Vobject a9,Cobject (Share.recompose (Share.bot,Share.top)))::nil) ((Vobject a1,Vobject a2,Vobject a9)::(Vobject a3,Vobject a4,Vobject a1)::(Vobject a5,Vobject a6,Vobject a3)::(Vobject a7,Vobject a8,Vobject a5)::nil),Impl_equation_system (nil) (a9::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.recompose (Share.bot,Share.top)))::nil)).
 Definition is17 :=(Impl_equation_system (nil) (a1::nil) (nil) (nil),Impl_equation_system (nil) (a1::nil) (nil) (nil)).
 Definition is18 :=(Impl_equation_system (nil) (a1::nil) (nil) (nil),Impl_equation_system (nil) (a2::nil) (nil) (nil)).
 Definition is19 :=(Impl_equation_system (nil) (a1::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (a3::nil) (nil) (nil)).
 Definition is20 :=(Impl_equation_system (nil) (a1::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (a2::nil) (nil) (nil)).
 Definition is21 :=(Impl_equation_system (nil) (a1::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a13,Vobject a14,Vobject a15)::nil),Impl_equation_system (nil) (a15::nil) (nil) (nil)).
 Definition is22 :=(Impl_equation_system (nil) (a1::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a9,Vobject a10,Vobject a11)::(Vobject a11,Vobject a12,Vobject a13)::(Vobject a13,Vobject a14,Vobject a15)::nil),Impl_equation_system (nil) (a14::nil) (nil) (nil)).
 Definition is23 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a1,Vobject a1)::(Vobject a2,Vobject a2,Vobject a2)::(Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (nil) ((Vobject a3,Cobject (Share.bot))::nil) (nil)).
 Definition is24 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a1,Vobject a1)::(Vobject a2,Vobject a2,Vobject a2)::(Vobject a1,Vobject a2,Vobject a3)::nil),Impl_equation_system (nil) (a3::nil) (nil) (nil)).
 Definition is25 :=(Impl_equation_system (nil) (nil) ((Vobject a,Cobject (Share.bot))::nil) (nil),Impl_equation_system (nil) (a::nil) (nil) (nil)).
 Definition is26 :=(Impl_equation_system (nil) (a::nil) ((Vobject a,Cobject (Share.bot))::nil) (nil),Impl_equation_system (nil) (a::nil) (nil) (nil)).
 Definition is27 :=(Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))),Vobject a,Vobject b)::nil),Impl_equation_system (nil) (a::nil) (nil) (nil)).
 Definition is28 :=(Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))),Vobject a,Vobject b)::nil),Impl_equation_system (nil) (b::nil) (nil) (nil)).
 Definition is29 :=(Impl_equation_system (nil) (a9::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::nil),Impl_equation_system (nil) (a1::nil) (nil) (nil)).
 Definition is30 :=(Impl_equation_system (nil) (a1::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::nil),Impl_equation_system (nil) (a9::nil) (nil) (nil)).
 Definition is31 :=(Impl_equation_system (nil) (a9::nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a4,Vobject a5)::(Vobject a5,Vobject a6,Vobject a7)::(Vobject a7,Vobject a8,Vobject a9)::(Vobject a8,Vobject a8,Vobject a8)::(Vobject a6,Vobject a6,Vobject a6)::(Vobject a4,Vobject a4,Vobject a4)::(Vobject a2,Vobject a2,Vobject a2)::nil),Impl_equation_system (nil) (a1::nil) (nil) (nil)).
 Definition is32 :=(Impl_equation_system (nil) (a::nil) (nil) ((Vobject a,Vobject a,Vobject a)::nil),Impl_equation_system (nil) (a1 ::nil) ((Vobject a5,Vobject a6)::(Vobject a2,Vobject a4)::(Vobject a4,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top)))))::nil) ((Vobject a1,Vobject a3,Vobject a8)::(Vobject a2,Vobject a8,Vobject a4)::nil)).
 Definition is33 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a,Vobject a,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))))::nil),Impl_equation_system (nil) (a::nil) (nil) (nil)).
 Definition is34 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))))),Vobject a)::nil),Impl_equation_system (nil) (a::nil) (nil) (nil)).
 Definition is35 :=(Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.top,Share.bot))))),Vobject a)::nil),Impl_equation_system (nil) (a::nil) (nil) (nil)).
 Definition is36 :=(Impl_equation_system (nil) (nil) (nil) (nil),Impl_equation_system (nil) (a ::nil) ((Vobject a,Vobject c)::(Vobject a,Cobject (Share.top))::(Vobject b,Cobject (Share.top))::nil) ((Vobject a,Vobject b,Vobject c)::nil)).
 Definition is37 :=(Impl_equation_system (nil) (a ::nil) ((Vobject a,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject b,Cobject (Share.recompose (Share.bot,Share.top)))::nil) ((Vobject a,Vobject b,Vobject c)::nil),Impl_equation_system (nil) (c::nil) ((Vobject c,Cobject (Share.top))::nil) (nil)).
 Definition is38 :=(Impl_equation_system (nil) (a ::nil) ((Vobject a,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject b,Cobject (Share.recompose (Share.bot,Share.top)))::nil) ((Vobject a,Vobject b,Vobject c)::nil),Impl_equation_system (nil) (c::nil) ((Vobject c,Cobject (Share.top))::nil) ((Vobject a,Vobject b,Vobject a)::nil)).
 Definition is39 :=(Impl_equation_system (nil) (a ::nil) ((Vobject a,Cobject (Share.recompose (Share.top,Share.bot)))::(Vobject b,Cobject (Share.recompose (Share.bot,Share.top)))::nil) ((Vobject a,Vobject b,Vobject c)::nil),Impl_equation_system (nil) (c::nil) ((Vobject c,Cobject (Share.top))::nil) ((Vobject a,Vobject b,Vobject c)::nil)).
 Definition is40 :=(Impl_equation_system (nil) (a1::nil) ((Vobject a1,Vobject a2)::nil) (nil),Impl_equation_system (nil) (a2::nil) (nil) (nil)).
 Definition is41 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a3,Vobject a4,Vobject a1)::(Vobject a5,Vobject a6,Vobject a3)::(Vobject a7,Vobject a8,Vobject a5)::nil),Impl_equation_system (nil) (a1 ::nil) (nil) (nil)).
 Definition is42 :=(Impl_equation_system (nil) (a8::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a3,Vobject a4,Vobject a1)::(Vobject a5,Vobject a6,Vobject a3)::(Vobject a7,Vobject a8,Vobject a5)::nil),Impl_equation_system (nil) (a5 ::nil) (nil) (nil)).
 Definition is43 :=(Impl_equation_system (nil) (a8::nil) (nil) ((Vobject a1,Vobject a2,Cobject (Share.top))::(Vobject a3,Vobject a4,Vobject a1)::(Vobject a5,Vobject a6,Vobject a3)::(Vobject a7,Vobject a8,Vobject a5)::nil),Impl_equation_system (nil) (a2::nil) (nil) (nil)).
 Definition is44 :=(Impl_equation_system (nil) (a1 ::nil) (nil) ((Vobject a2,Vobject a2,Vobject a1)::nil),Impl_equation_system (nil) (a2 ::nil) (nil) (nil)).
 Definition is45 :=(Impl_equation_system (nil) (a1::nil) (nil) ((Vobject a2,Vobject a3,Vobject a1)::nil),Impl_equation_system (nil) (a2::nil) (nil) (nil)).
 Definition is46 :=(Impl_equation_system (nil) (nil) (nil) ((Vobject a1,Vobject a2,Vobject a3)::(Vobject a3,Vobject a2,Vobject a5)::(Vobject a3,Vobject a5,Vobject a2)::(Vobject a1,Vobject a4,Vobject a6)::(Vobject a5,Vobject a3,Vobject a8)::nil),Impl_equation_system (nil) (a1::nil) (nil) (nil)).
 Definition is47 :=(Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.top),Cobject (Share.top),Cobject (Share.top))::nil),Impl_equation_system (nil) (a1 ::nil) ((Vobject a1,Vobject a8)::(Vobject a1,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot)))::(Vobject a8,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::nil) ((Vobject a3,Vobject a4,Vobject a5)::nil)).
 Definition is48 :=(Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.top))::nil),Impl_equation_system (nil) (a1 ::nil) ((Vobject a1,Vobject a8)::(Vobject a1,Cobject (Share.recompose (Share.recompose (Share.recompose (Share.recompose (Share.top,Share.bot),Share.bot),Share.bot),Share.bot)))::(Vobject a8,Cobject (Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.recompose (Share.bot,Share.top))))))::nil) ((Vobject a3,Vobject a4,Vobject a5)::nil)).
 Definition is49 :=(Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.recompose (Share.bot,Share.top)),Cobject (Share.recompose (Share.top,Share.bot)),Cobject (Share.top))::nil),Impl_equation_system (nil) (nil) (nil) ((Cobject (Share.recompose (Share.recompose (Share.bot,Share.top),Share.recompose (Share.bot,Share.top))),Cobject (Share.recompose (Share.recompose (Share.top,Share.bot),Share.recompose (Share.top,Share.bot))),Cobject (Share.top))::nil)).

 Definition l := 
 (ses1::ses2::ses3::ses4::ses5::ses6::(*ses7::ses8::ses9::*)ses10::
  ses11::ses12::ses13::ses14::ses15::ses16::ses17::ses18::ses19::ses20::
  ses21::ses22::ses23::ses24::ses25::ses26::ses27::ses28::ses29::ses30::
  ses31::ses32::ses33::ses34::ses35::ses36::ses37::ses38::ses39::ses40::
  ses41::ses42::ses43::ses44::ses45::ses46::ses47::ses48::ses49::ses50::
  ses51::ses52::ses53::nil).
 (*
 Time Eval compute in (map SATsolver l).
 *)
 (*16.1s*)

 Definition l' :=
 (
 is1::is2::is3::is4::is5::is6::is7::is8::is9::is10::
 (*is11::*)is12::is13::is14::is15::is16::is17::is18::is19::is20::
 is21::is22::is23::is24::is25::is26::is27::is28::is29::is30::
 is31::is32::is33::is34::is35::is36::is37::is38::is39::is40::
 is41::is42::is43::is44::is45::is46::is47::is48::is49::nil
 ).
 (*
 Time Eval compute in (map IMPLsolver l').
 *)
 (*8.9s*)

End Tester.


